name: alchemy_web3
description: An Alchemy Platform client for Flutter & Dart
version: 0.1.4
homepage: https://github.com/oliverbytes/alchemy_web3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  logger: ^2.0.2+1
  decimal: ^2.3.2
  either_dart: ^0.4.0
  # NETWORK
  dio: ^5.1.1
  json_rpc_2: ^3.0.2
  web_socket_channel: ^2.3.0
  # CRYPTO
  pointycastle: ^3.6.2
  convert: ^3.1.1
  # WEB3
  web3dart: ^2.6.1


dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.4
