name: alchemy_web3
description: An Alchemy Platform client for Flutter & Dart
version: 0.1.0
homepage: https://github.com/oliverbytes/alchemy_web3

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  console_mixin: ^0.0.1
  logger: ^1.1.0
  either_dart: ^0.3.0
  # NETWORK
  dio: ^4.0.3
  json_rpc_2: ^3.0.2
  web_socket_channel: ^2.1.0
  # CRYPTO
  pointycastle: ^3.6.2
  convert: ^3.1.1
  # WEB3
  web3dart: ^2.3.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
